//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_chat
    {
        public int STT { get; set; }
        public string Wait_mess { get; set; }
        public int Id_group { get; set; }
        public int Id { get; set; }
    
        public virtual Group_chat Group_chat { get; set; }
        public virtual Person Person { get; set; }
    }
}
